%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
<<<<<<< HEAD
   fx: 376
   fy: 376
   cx: 376
=======
   fx: 320
   fy: 320
   cx: 320
>>>>>>> adding-vins-config-file
   cy: 240
